<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Retry</title>
    <link rel="stylesheet" href="./css/styles.css" />
    <script src="./js/main.js"></script>
  </head>
  <body>
    <h1>WDD 330 Portfolio</h1>
    <h2>Retry</h2>

    <h3>
      Say you have a function primitiveMultiply that in 20 percent of cases
      multiplies two numbers and in the other 80 percent of cases raises an
      exception of type MultiplicatorUnitFailure. Write a function that wraps
      this clunky function and just keeps trying until a call succeeds, after
      which it returns the result.
    </h3>

    <h3>Make sure you handle only the exceptions you are trying to handle.</h3>

    <h3>
      Use the === operator, or something equivalent such as indexOf, to
      determine whether two values are the same.
    </h3>

    <h3>
      <h3>class MultiplicatorUnitFailure extends Error {}</h3>

      <h3>function primitiveMultiply(a, b) {</h3>
      <h3>if (Math.random() < 0.2) {</h3>
      <h3>return a * b;</h3>
      <h3>} else {</h3>
      <h3>throw new MultiplicatorUnitFailure("Klunk");</h3>
      <h3>}</h3>
      <h3>}</h3>

      <h3>function reliableMultiply(a, b) {</h3>
      <h3> // Your code here. </h3>

      <h3>console.log(reliableMultiply(8, 8));</h3>
      <h3>// → 64</h3>
    </h3>

    <h3>
      Hint...The call to primitiveMultiply should definitely happen in a try
      block. The corresponding catch block should rethrow the exception when it
      is not an instance of MultiplicatorUnitFailure and ensure the call is
      retried when it is.
    </h3>

    <h3>
      To do the retrying, you can either use a loop that stops only when a call
      succeeds—as in the look example earlier in this chapter—or use recursion
      and hope you don’t get a string of failures so long that it overflows the
      stack (which is a pretty safe bet).
    </h3>

    <h3>Check the console for the answers.</h3>

    <script>
      class MultiplicatorUnitFailure extends Error {}

    function primitiveMultiply(a, b) {
      if (Math.random() < 0.2) {
        return a * b;
      } else {
        throw new MultiplicatorUnitFailure("Klunk");
      }
    }

    function reliableMultiply(a, b) {
      for (;;) {
        try {
          return primitiveMultiply(a, b);
        } catch (e) {
          if (!(e instanceof MultiplicatorUnitFailure))
            throw e;
        }
      }
    }

    console.log(reliableMultiply(8, 8));
    // → 64
    </script>
  </body>
</html>
